export const SET_TASKS_ARRAY     = 'SET_TASKS_ARRAY';
export const SET_CURRENT_TASK    = 'SET_CURRENT_TASK';
export const SET_CURRENT_FILTER  = 'SET_CURRENT_FILTER';
export const SET_OPEN_EDIT_BLOCK = 'SET_OPEN_EDIT_BLOCK';
